#!/bin/bash
# viall - open a set of files with vim in a screen session, one tab per file
# (c) 2015 Luc Deschenaux
# LICENSE: GPLv3 - http://www.gnu.org/licenses/gpl-3.0.txt

find $@ | sort -u | while read l ; do vi $l ; done

